name: Deploy Strapi to VPS with Docker Compose

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/strapi:latest .

      # Push image to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/strapi:latest

      # Copy docker-compose file ke Server (optional)
      - name: Upload docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/apps/folearn/"

      # Deploy ke server
      - name: Run docker-compose on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/folearn
            echo "Login GHCR..."
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pull latest image..."
            docker compose pull

            echo "Recreate containers..."
            docker compose up -d

            echo "Prune unused images..."
            docker image prune -f
